### ISSUE TITLE
Cannot apply patch

### ISSUE THREAD

**Issue by Nigcra** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#11]
Hello,

I own the original game in several variations. I have tried several No-CD executables (pretty much everything I could find on known sites), but none of them could run the patch. I didn't check the checksum, but if I don't find anything under this checksum, I don't need to check it. I would like to play the whole thing in German and not in English. Can anyone help me?

**Comment by FaithBeam** [comment]
Hi @Nigcra, do you have the original sims as in no expansions, or do you have the Sims Complete Collection?

**Comment by Nigcra** [comment]
Hi, I have tried the Sims Deluxe and the Collection.

**Comment by FaithBeam** [comment]
Can you install the Complete Collection, use this nocd exe, and then try the patch please?
http://www.gameburnworld.com/dl/dl2/m.php?p=TheSimsCompleteCollectionv1.91NoCDFixedexeEng.rar

You will need 7-zip or WinRar to extract this.

**Comment by Nigcra** [comment]
Get exactly the same error as seen above. Additionally both the EXE and the backup EXE are broken and the game won't start anymore.

**Comment by FaithBeam** [comment]
If you try just the nocd exe that I posted above without patching does the game load?

**Comment by Nigcra** [comment]
![image](https://user-images.githubusercontent.com/26165631/90073449-7f5d2680-dcf9-11ea-8e1b-0529559d4edb.png)

yes that works

**Comment by FaithBeam** [comment]
Try this release: https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.16.0/Sims1WidescreenPatcher.1.16.0.zip

If this doesn't work please post the contents of the SimsWidescreenPatcher.log that gets created.

**Comment by Nigcra** [comment]
Hi, thanks for your efforts, 

here is the error and log file: 

![image](https://user-images.githubusercontent.com/26165631/90424555-99628480-e0be-11ea-8c2f-cf32ddb1ad98.png)

[SimsWidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/5085810/SimsWidescreenPatcher.log)

**Comment by FaithBeam** [comment]
@Nigcra I see the issue now. You extracted my patch to the same folder with your Sims.exe. Extract the patch anywhere other than that and try patching again. The reason it fails is a combination of the sims install having a directory with UIGraphics and my patch also using the same directory name. When you click patch, it will delete the images from the sims install, and in this instance since they both share the same directory name, deletes the images from my patch before it can scale them.

I'll make an update to handle this but for now just extract my patch to any other folder than the Sims installation directory.

**Comment by FaithBeam** [comment]
@Nigcra Created a new release which should fix this issue. Try it out: https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.17.0/Sims1WidescreenPatcher.1.17.0.zip

**Comment by Nigcra** [comment]
That worked, thank you very much!!

**Comment by FaithBeam** [comment]
You're welcome! :)
