### ISSUE TITLE
Just found out that 3.10.0 can't seem to turn pages in-game

### ISSUE THREAD

**Issue by ralcatalpa** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#111]
Hi! I found this amazing high-res patch a few months ago and have been utterly amazed by how it works so fine even I haven't had the time to really play The Sims 1 over the past months.
Today I downloaded 3.10.0 build and uninstalled 3.9.0 settings before patching with 3.10.0, then I ran the game and found out that both 3.9.0 and 3.10.0 seems to be lacking the arrow where I can turn pages when I browse buy/build mode.

This is the original .exe file. as you can see, there is an arrow on the right side that helps me turn pages.
![image](https://github.com/user-attachments/assets/93e5ad74-8db5-4e93-a04d-f56ed70f8669)

This is what I have when I patched the original .exe file with high-res patch, the arrow is gone: (clearly there are more floor styles to be shown but I can't go to them)
![image](https://github.com/user-attachments/assets/6650121d-b2f4-470d-8e5f-26ac7074dfca)

Even the arrow is not showing I'm still super grateful for the developers of this patch. However it'll be nice if someone can tell me whether it's me not using this patch correctly/that there is a hotkey to turn pages, or there is a minor fix needed for the current patch?

(And I'm sorry that I posted this question in Discussions page before I discovered Issues section.)

Thank you!!

**Comment by FaithBeam** [comment]
@ralcatalpa What resolution did you patch to? On 1280x720, I was able to page through all the choices
![image](https://github.com/user-attachments/assets/bb1d0c26-0e2c-4d32-9214-cd35d9e1f8be)

**Comment by ralcatalpa** [comment]
> @ralcatalpa What resolution did you patch to? On 1280x720, I was able to page through all the choices ![image](https://private-user-images.githubusercontent.com/32502411/382468259-bb1d0c26-0e2c-4d32-9214-cd35d9e1f8be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDkyNzQsIm5iZiI6MTczMDU0ODk3NCwicGF0aCI6Ii8zMjUwMjQxMS8zODI0NjgyNTktYmIxZDBjMjYtMGUyYy00ZDMyLTkyMTQtY2QzNWQ5ZTFmOGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDEyMDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMmY5OTIzMzc2YmVlYzZiYzM4N2IzYWEzY2JkOWQ1MzU0N2VjZTE0MjAwZWQwYTJiZmM4ZWI0ZTQxNGJkYTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OfF7V5JUZX0SIWW-rnPjIE5PlWL7PtckY1f95hWVSlk)

Hi! Thank you for your reply!

I patch to 2048*1536 and have enabled borderless. I use DDrawCompat0.5.4. This is my setting:


![image](https://github.com/user-attachments/assets/b5722705-334a-441f-b0b4-8ed59d167e6b)

**Comment by ralcatalpa** [comment]
Hello, hope everything's going well with IFF! Could you help me with this bug with the Widescreen Patcher? Thanks!!

**Comment by FaithBeam** [comment]
> Hello, hope everything's going well with IFF! Could you help me with this bug with the Widescreen Patcher? Thanks!!

Unfortunately, I cannot solve this issue at this time. This requires more skill to fix than I currently have. There are two widths known that have this issue, 1600 and now 2048. I'm going to guess the problem arises because of some function in the game that calculates how many icons to place in the buy menu adds one too many which leaves no room for the page arrow. 

The only solution for now is to choose a different resolution.

**Comment by ralcatalpa** [comment]
Hi! Thanks for your reply!
I changed the resolution to 1440*1080 and it feels great, just like when I first played The Sims, perhaps it's because the window is in the shape of a square, which looks great!
