### ISSUE TITLE
Feat: Career Editor

### ISSUE THREAD

**Issue by FaithBeam** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#114]
Wants:

* Edit non-string values for careers
* Presets with modified career values for balance inspired by [link](https://old.reddit.com/r/thesims1/comments/xzj42v/careers_suck_heres_why_and_how_to_fix_them_maybe/)

Inspiration from Iff Pencil:

![image](https://github.com/user-attachments/assets/d2c5de9e-5293-4464-bded-94ab030851d9)

**Comment by ralcatalpa** [comment]
Looking forward to it!!

**Comment by FaithBeam** [comment]
Successfully loading the careers with jobs:
<img width="785" alt="Screenshot 2024-11-19 at 4 58 46 PM" src="https://github.com/user-attachments/assets/bdb85b76-99d2-46bc-b878-03d3eba83e93">

**Comment by FaithBeam** [comment]
We're loading all data now:
<img width="893" alt="Screenshot 2024-11-19 at 6 44 29 PM" src="https://github.com/user-attachments/assets/eac42da0-e17d-4fe5-bb12-b548577620a5">

**Comment by FaithBeam** [comment]
![image](https://github.com/user-attachments/assets/ff66f141-61b7-4d10-8158-ec50aa59d948)

**Comment by FaithBeam** [comment]
There's a bug when setting values to 0 which causes the career path to break, but non-zero values work. I changed Claire's paramedic vehicle to clown car.
![Screenshot 2024-11-21 110707](https://github.com/user-attachments/assets/07b5d62c-0ecf-4d12-8043-d963b1a468ce)

**Comment by FaithBeam** [comment]
I think the iff bugs are ironed out. I'll likely release this feature in a week.
