### ISSUE TITLE
Anti-aliasing option is missing?

### ISSUE THREAD

**Issue by Prisoner416** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#23]
I tried using the latest build of this patch, but for some reason the store wasn't showing object previews properly, so I reverted to my old patch version that worked.

However, one thing that annoys me, and has ever since I got the complete collection, is that anti-aliasing is missing from the options. I remember it being an option on the full games, used to have almost all the expansions. I'm not certain if it was removed in complete or if there's a way to restore it.

**Comment by FaithBeam** [comment]
@Prisoner416 

Can you get me a screenshot of the bad object previews? I tried it with the 1.23.0-beta.1 patch and it looks normal if what we're talking about are the same.

![zopfli_Sims Screenshot 2021 01 22 - 06 28 01 41](https://user-images.githubusercontent.com/32502411/105485734-5747fb00-5c7b-11eb-8c9f-bb0dc1ff98f7.png)

The antialiasing must have been removed in the Complete Collection then. However, you can force MSAA through dgvoodoo2 that you can choose to install in my patch. I added a page to the wiki with comparison screenshots and how to apply it [here](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/wiki/Antialiasing).
