### ISSUE TITLE
Requesting patcher for Sims 1 Original

### ISSUE THREAD

**Issue by slowtorta** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#25]
**Installed Sims Version**
Sims 1 Original:  **Link removed**
**Are you using a nocd exe / crack?**
Yes, it's provided with the game download.

**Describe the issue**
Dear sir FaithBeam! You're truly amazing person and I'm very grateful for your work ❤️ I'd really love the first version of the game to work in higher resolutions. Is it possible to arrange?

**Comment by FaithBeam** [comment]
@slowtorta 

Thank you for the kind words. I actually made it so you can use my patch with different Sims versions, but I can't really test them. I get an error while trying to play the patched Sims on a VM. My patcher successfully runs, but beyond that I don't know. Give it a try!

I removed the link you provided. I don't have a personal problem with the link you posted, but I want to protect this Github from any funny business from foreign actors. I hope you understand :)

**Comment by slowtorta** [comment]
It worked as charm :) I didn't know you can use it with any game version! https://ibb.co/CwGr6fW 🤗 Sims 1 Vacation was my favorite version of all of them, means now when I will find a working download I can play it again :p Thanks!

**Comment by FaithBeam** [comment]
@slowtorta Glad it worked for you :)
