### ISSUE TITLE
no .exe file in download

### ISSUE THREAD

**Issue by wiseiam** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#30]
**Installed Sims Version**
Sims 1 no expansions, Sims 1 Complete Collection, etc.

**Are you using a nocd exe / crack?**

**Describe the issue. Include screenshots if you can**

**What are the steps to reproduce the issue?**

**Please attach the generated log file SimsWidescreenPatcher.log**

**Comment by FaithBeam** [comment]
Which download are you talking about? You want to click the Sims1WidescreenPatcher zip, not the source code zips. Here is a direct link https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/download/1.23.0-beta.2/Sims1WidescreenPatcher.1.23.0-beta.2+x86.zip.
![image](https://user-images.githubusercontent.com/32502411/124494041-5b2c8d00-dd84-11eb-8dcc-d19b9e03d51c.png)

**Comment by wiseiam** [comment]
Omgosh! Ok thank you so much!

**Comment by FaithBeam** [comment]
You're welcome! :)
