### ISSUE TITLE
DDrawCompat has lower latency and better performance than dgVoodoo2

### ISSUE THREAD

**Issue by mrpenguinb** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#31]
dgVoodoo2 works competently, but has latency and performance issues with The Sims 1 (has more overhead). And some graphical glitches are resolved as well when running the game in widescreen.

DDrawCompat is aimed at fixing games that use DirectDraw. Using this with The Sims 1 feels amazing, full 60 fps and even busy lots with lots of sims can be smooth.

At the very least, it would be nice to have an option in the widescreen patcher to choose either dgVoodoo2 or DDrawCompat with DDrawCompat recommended (preferrable).

**If dgVoodoo2 is already installed, installing DDrawCompat requires just replacing dgVoodoo2's DDraw.dll with DDrawCompat's ddraw.dll**

**Comment by FaithBeam** [comment]
@mrpenguinb Yea, this looks to be almost completely better than dgVoodoo2. I experience some weirdness on startup however. The framerate tanks, and it seems like loading the neighborhood screen takes longer? I can imagine some users may create issues about "sims being frozen" when it's just ddrawcompat doing whatever it does on load.

I might add this. I need to test it more.

**Comment by mrpenguinb** [comment]
> 
> 
> @mrpenguinb This looks to be almost completely better than dgVoodoo2. I experience some weirdness on startup however. The framerate tanks, and it seems like loading the neighborhood screen takes longer? I can imagine some users may create issues about "sims being frozen" when it's just ddrawcompat doing whatever it does on load.
> 
> I might add this. I need to test it more.

The neighborhood screen does take longer, but it speeds up over time I think.
There is always lag with the words scrolling (under the logo) when the game starts. I've already added an issue to DDrawCompat's repo about it. 
It is a worthwhile option to add, with less overhead and complexity compared to dgVoodoo2 IMO.

**Comment by FaithBeam** [comment]
@mrpenguinb Latest release has DDrawCompat: https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/1.23.0-beta.3

**Comment by mrpenguinb** [comment]
> 
> 
> @mrpenguinb Latest release has DDrawCompat: https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/1.23.0-beta.3

Fantastic! Has it made the game more enjoyable to play for you? (it has for me).
Using DDrawCompat makes the game run just like how it does on Windows XP before DirectDraw was deprecated performance-wise.

**Comment by FaithBeam** [comment]
It definitely provides a superior experience. That said, I haven't really played The Sims for five years. I'm glad ddrawcompat exists though :)
