### ISSUE TITLE
Patcher not recognising No-CD for EP01 and EP02

### ISSUE THREAD

**Issue by Elielzices** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#33]
**Installed Sims Version**
Sims 1 basegame + gradually instaling

**Are you using a nocd exe / crack?**
Yes. I tested every nocd that I collected. I'm using a nocd that works for Brazilian game language (Idk if there's a difference).
I shared in this folder (https://1drv.ms/u/s!AjsCZzvH1IFemK9Wp7Azw779gfQGaQ?e=3n247W) copies of the files

**Describe the issue. Include screenshots if you can**
When patching, I select the exe and returns the message: "This executable cannot  be edited. Please make sure you're using a valid no cd executable."
When editing in HEX to mimic  WSGF's way to manually turn HD/FHD, the values described are not found

**What are the steps to reproduce the issue?**
Described above

**Please attach the generated log file SimsWidescreenPatcher.log**
https://1drv.ms/u/s!AjsCZzvH1IFemK9mNUXQF7PKp0l3mA?e=WKM4zq

P.S.: I  couldn't upload directly to Github so I had to sent those OneDrive links, sorry

**Comment by FaithBeam** [comment]
@Elielzices 
Hello! Yes, I too cannot find the offsets for width and height or ep 1 and 2. The exe for ep 1 is weird, 157kb vs 2+mb the other exes. This patch does nearly the same thing as documented in WSGF so if it doesn't work with that, it won't work with my program I'm sorry to say :(

**Comment by Elielzices** [comment]
@FaithBeam 
Thanks for the answer. I was so glad when I heard someone took the time to automatize the WSGF steps, thanks for it too.

Yeah, I was wondering if the problem was just with me (my nocd) or if it was a general problem.
Thanks again
