### ISSUE TITLE
Neighborhood screen for Vacation area bugged out (possibly others?) v1.24.0-beta.1

### ISSUE THREAD

**Issue by DiabloStorm** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#39]
![vacation island](https://user-images.githubusercontent.com/63818362/131487449-80997d90-1b27-4398-8625-0857341eaadd.PNG)

**Comment by FaithBeam** [comment]
@DiabloStorm Hello! I can confirm this issue. This comes from me improperly naming a bmp file. Can you try this version? It should fix this.

[Sims1WidescreenPatcher.1.24.0-beta.2.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/7083411/Sims1WidescreenPatcher.1.24.0-beta.2.zip)

**Comment by DiabloStorm** [comment]
![still bugged](https://user-images.githubusercontent.com/63818362/131865330-6a3f5dc6-dbc6-4a6e-b2ed-bfe476cb21ae.PNG)
Bad news, areas are still bugged like this. This is when you're in game travelling to other areas while playing, not just switching neighborhood views with no sims doing things in the background...

I jump into the magic town hole and get this screen, same with the vacation screen after calling transportation.

**Comment by FaithBeam** [comment]
That's strange. I was getting the same issue as you with 1.24.0-beta.1, but I'm pretty sure I fixed it in 1.24.0-beta.2 (at least for me). Can you paste the Sims1WidescreenPatcher.log, and you're using the Complete Collection correct?

**Comment by DiabloStorm** [comment]
So, for the record I'm using my original cds, essentially the same as complete collection, plus a discless .exe So, confirmation that this works for people like me :P 

Anyway, looks like this + the last patch fixed them all. I just went through each one to check. 

Thanks for everything here.
