### ISSUE TITLE
Sims1WidescreenPatcher.exe keeps running in the background and won't show up

### ISSUE THREAD

**Issue by yacort** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#42]
**Installed Sims Version**
Sims 1 Complete Collection, etc.

**Are you using a nocd exe / crack?**
yes
**Describe the issue. Include screenshots if you can**
After the first time using it, I wanted to open the executable again and it only keeps going in the background. Tried everything but no dice.
**What are the steps to reproduce the issue?**
-Open the program for the first time
-Use it to patch a cracked exe to the desired resolution
-Exit the program, test if it runs and try to open it again.

**Please attach the generated log file SimsWidescreenPatcher.log*
[Sims1WidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/7413927/Sims1WidescreenPatcher.log)
*

**Comment by yacort** [comment]
> @yacort Try these two, I've changed some settings around the onclose method to hopefully kill it when the X button is clicked, and made the patch process single threaded, respectively. [Sims1WidescreenPatcher.2.0.3-beta.1.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/7425405/Sims1WidescreenPatcher.2.0.3-beta.1.zip) [Sims1WidescreenPatcher.2.0.3-beta.2.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/7425538/Sims1WidescreenPatcher.2.0.3-beta.2.zip) There are two cases I'd like you to test out after killing any existing process:
> 
> 1. Run the patch like normal and see what happens. Patch, exit, try to run patch again.
> 2. Kill any existing processes, run the program without patching, close it, and try running it again. This would tell me if there was potentially runaway threads when the patch occurs.

Is still behaving like the others versions, but now at least it appears in the windows' regular taskmanager
![Screenshot_8](https://user-images.githubusercontent.com/59181165/139510328-4be89e40-dfde-4dfe-9d7d-ba34e9c59c14.png)
![Screenshot_7](https://user-images.githubusercontent.com/59181165/139510329-c6983acb-2599-4fc5-a79d-43d03a140263.png)
Sorry for my late reply and thanks in advance!

**Comment by FaithBeam** [comment]
@yacort Try this release. It is another attempt force close the application on shutdown.
[Sims1WidescreenPatcher.2.0.3-beta.3.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/7490400/Sims1WidescreenPatcher.2.0.3-beta.3.zip)
