### ISSUE TITLE
Resolution 1600x900: next / back arrows in Build / Buy mode are gone

### ISSUE THREAD

**Issue by shenna** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#5]
Hello! Thanks for making this public.

I've adapted it to 1600x900 resolution. It runs perfectly fun yet with one bug: next / back arrows in all product pages are gone. They're in place in the Build mode tho, invisible but show up on hover.

This is my screenshot:
https://cdn.discordapp.com/attachments/416652374137110538/681213972325597305/unknown.png

This is from other person who tried 1600x900:
https://cdn.discordapp.com/attachments/416652374137110538/681280558898348037/The_Sims_Makin_Magic_2_23_2020_3_25_14_PM.png

Is there anything you could do?

Thanks.

**Comment by FaithBeam** [comment]
@shenna 

I was able to reproduce this bug with that resolution, and I have no idea how to solve it. I will look around to see if there is something I can do. In the meantime, try using a different resolution. I can see the next / back arrows with:
* 1280x720
* 1366x768
* 1920x1080

Proof shown here: https://imgur.com/a/SiSu3Bp

I'll update the README.md with this information.

**Comment by shenna** [comment]
@FaithBeam 

Gotcha. Thank you 🖖
