### ISSUE TITLE
Patcher on macOS Wineskin

### ISSUE THREAD

**Issue by xactionx59** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#54]
**Installed Sims Version**
Sims 1 Complete Collection (FRENCH version) on macOS 12.4 with Wineskin

**Are you using a nocd exe / crack?**
Yes

**Describe the issue. Include screenshots if you can**
Hi!  👋 First of all thank you for the work you have done! I've been using this patch for years on Windows and it's always worked fine. Now, I'd like to play The Sims 1 on my Mac (French version) and I have this error message when I want to launch the patch from Wineskin (I don't know if the method is different on Linux).

**What are the steps to reproduce the issue?**
- New blank wrapper (wineskin 2.9.1.1) with engine (WS11WineCX21.2.0)
- Clean installation of Sims 1
- The first launch of the game doing well with this settings :
<img width="798" alt="Capture d’écran 2022-07-19 à 10 39 47" src="https://user-images.githubusercontent.com/38098554/179722891-aca755d4-6f49-4a47-a77c-e8777765d30a.png">

- Installation of MS .NET 4.7.2 with Winetricks
- Latest version patch folder is here (s1wp) :
<img width="950" alt="Capture d’écran 2022-07-19 à 11 56 09" src="https://user-images.githubusercontent.com/38098554/179723292-5e59cb7a-d4ee-4232-a114-dc743ab33164.png">

- And... error when I try to launch it :

<img width="372" alt="Capture d’écran 2022-07-19 à 10 40 50" src="https://user-images.githubusercontent.com/38098554/179722334-4253dae1-0c56-4684-b3f9-39d9a39d72c4.png">

**Please attach the generated log file SimsWidescreenPatcher.log**
[Sims1WidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/9139596/Sims1WidescreenPatcher.log)

Thanks a lot ! :)

**Comment by FaithBeam** [comment]
@xactionx59 Hello! I'm glad you enjoy the program! Wineskin winery stopped working with my patcher a few months ago from one of its updates. There are two options you can try:
1. Run the latest patcher with CodeWeavers Crossover
2. Run the patcher I've attached in a wine prefix with only dotnet40 installed. If you try to run this in your wineskin with dotnet472 installed, it may not work. This version doesn't have some of the quality of life stuff the latest version of the patcher has and it will look like it has frozen when it's patching [Sims1WidescreenPatcher.zip](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/9154327/Sims1WidescreenPatcher.zip)

Let me know if either of these work for you.

**Comment by xactionx59** [comment]
Hello! Thanks a lot for your reply!

I've tried the first and second option. All of these works well! You're the best! :) Thanks a lot!

<img width="1440" alt="Capture d’écran 2022-07-21 à 14 56 56" src="https://user-images.githubusercontent.com/38098554/180224965-9e8ac050-7338-47e8-9a65-0a3653924ef6.png">

<img width="1440" alt="Capture d’écran 2022-07-21 à 14 57 56" src="https://user-images.githubusercontent.com/38098554/180224980-1926af12-f67e-4b31-807e-1106e846c50c.png">
