### ISSUE TITLE
Invalid URI: The hostname could not be parsed.

### ISSUE THREAD

**Issue by ct2057** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#55]
**Installed Sims Version**
Sims 1 Complete Collection

**Are you using a nocd exe / crack?**
N/A

**Describe the issue. Include screenshots if you can**
When attempting to run Sims1WidescreenPatcher via Windows Explorer, the application simply does not run. However, if I run the application via the CLI the app seems to vomit, starting with an error that there was an Invalid URI (see attached output). There also seems to be a reference to a home directory, at the bottom of log, that is unfamiliar.

**What are the steps to reproduce the issue?**
N/A

**Please attach the generated log file SimsWidescreenPatcher.log**
[Sims1WidescreenPatcher.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/9268322/Sims1WidescreenPatcher.log)
[CLI_Output.txt](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/9268298/CLI_Output.txt)

**Comment by FaithBeam** [comment]
That is bizarre. I don't create a URI in my code at all which is confusing me. It dies right as it tries to show the GUI according to the cli output. Which version of Windows are you using, do you have a non-standard antivirus, does the Event Viewer > Windows Logs > Application show anything after you try to run the application?

That path in the logs is my local computer dev path for the application. They're included in the pdbs for some reason. Pdbs contain debug information and show more useful stacktraces when a program crashes. Clearly not useful enough from what we can see :D

If you can wait a few days I'll have the 3.0.0 version ready which is a complete rewrite and will probably solve this issue.

**Comment by FaithBeam** [comment]
I just released a beta of 3.0.0 if you'd like to try that https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/3.0.0-beta.1.

**Comment by ct2057** [comment]
Hello, so I ran the version 3.0.0 beta (macOS version) and all I can say is, seeing one of my childhood favourite games running in all its (now) 4K glory is such a sight to behold! Thank you so much for your help, and for this amazing app. 

I will mention however that v3.0.0 (for Windows) of the app - running under a Wine environment - does not appear to work; a little more feedback this time compared to the current 'live' version, but not by much: a small window appears that simply says "Bad EXE format for".

Happy to consider this issue resolved, and close the ticket.
