### ISSUE TITLE
Custom Resolution Issue

### ISSUE THREAD

**Issue by acsibubu** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#57]
Hello, any ideas on how to get the game running with a  custom resolution of 854×480?

**Comment by FaithBeam** [comment]
Hello! For custom resolutions you'll need to do two things:
1. Add the resolution in the patcher by clicking the resolution drop down, scrolling to the bottom of the list, and selecting \<Custom Resolution\> 
<img width="452" alt="Sims1WidescreenPatcher_WKXimLHXa9" src="https://user-images.githubusercontent.com/32502411/192167857-77f34639-b6ed-49a7-979a-e5d41edb5b9a.png">
<img width="340" alt="Sims1WidescreenPatcher_kbJRUgQhQi" src="https://user-images.githubusercontent.com/32502411/192167864-6f3f5944-6721-49d9-bb6a-0d51e69fd381.png">

2. The game will need to run windowed to not crash. Here are some instructions: https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/wiki/Windowed,-Borderless-Windowed,-FSR-Upscaling

**Comment by acsibubu** [comment]
![image](https://user-images.githubusercontent.com/105495719/192168431-596eb6a3-0b69-4be4-b82d-6fbfd402d940.png)
Thank you for the quick reply!
Unfortunately using this option ends up with the above error, any othe option causes some weird lagging when scrolling,

**Comment by FaithBeam** [comment]
Does a log file get dropped in the magpie folder? If so, can you paste it?

**Comment by acsibubu** [comment]
I got it working fine, had to change the default graphics processor to the integrated one in the NVIDIA control pannel.

**Comment by FaithBeam** [comment]
Excellent! Thank you for posting your solution!
