### ISSUE TITLE
Application appears to close after clicking Patch

### ISSUE THREAD

**Issue by Cinibonswirl26** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#6]
I've run this program as administrator, but it closes after I click patch

**Comment by FaithBeam** [comment]
@Cinibonswirl26 

Can you try [this release](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/releases/tag/v.1.2.0) and tell me what the error message is? This includes logging so it will hopefully capture whatever error you're getting.

Did you have the dgvoodoo2 checkbox checked when this happened?

Try copying your sims.exe to your desktop, run the program without administrator, patch the sims.exe on your desktop, and copy the sims.exe and UIGraphics to your sims directory.
