### ISSUE TITLE
(MacBook Pro 2019/MacOS Monterey Version 12.6) 

### ISSUE THREAD

**Issue by MonDiz26** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#60]
I'm not sure what to do after downloading [Sims1WidescreenPatcher.3.0.0+osx.x64.zip] and Source code
(zip) from your latest drop. I need a step-by-step process how to get it into my laptop I tried about 10 times and I still didn't get anywhere. Please help thank you! I'm new to all of this coding and what not but I do want the sims complete collection on my laptop.

I have also put in the terminal command you have put as well and it says "no such file: Sims1WidescreenPatcher.app/ but I have it on my download file on Finder

When I open my Sims 1 Widescreen Patcher I can't open any files from the "Sims-1-Complete-Collection-Widescreen-Patcher-3.0.0"

Not sure what i'm doing wrong but any help will be great!

**Comment by FaithBeam** [comment]
You can delete the source code zip because it's not needed to run the patcher. This is a step by step YouTube guide for the patcher: https://www.youtube.com/watch?v=hOy1boR1_Go
