### ISSUE TITLE
The game is uncentered

### ISSUE THREAD

**Issue by HafidzJL** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#62]
Hello I'm new here and sorry if my english bad.

I try this patcher for a few days ago. It's all run smoothly except the game isn't run in the center of my monitor and kind of cropped.
I set my monitor in 1920x1080 so I patch the sims.exe in same resolution.
I try to find the problem and trying windowed method with -w -r 1920x1080 hope the game will open in the center, sadly it's not working.
So I uninstall the patch and just play normaly.
I hope there is a way to solve the problem.

I'm using Lenovo Ideapad Gaming 3 to play.

Here a screenshots to show how the game running when I patch it.
![Sims](https://user-images.githubusercontent.com/121550857/209801060-91c311a5-0a0a-4b86-a166-946eba81b685.png)

**Comment by FaithBeam** [comment]
@HafidzJL Hello! Try changing the dpi settings for The Sims shortcut. https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/issues/28#issuecomment-845843938

**Comment by HafidzJL** [comment]
> @HafidzJL Hello! Try changing the dpi settings for The Sims shortcut. [#28 (comment)](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/issues/28#issuecomment-845843938)

It's work... thank you for the solution, and sorry I should read all the issues properly.

**Comment by FaithBeam** [comment]
@HafidzJL No worries! It can be difficult to know what to search for anyway. I'm glad it works for you :)
