### ISSUE TITLE
v 3.2.2 "Patch" button is grayed out

### ISSUE THREAD

**Issue by thatcoolmonkey** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#63]
Hi there! I'm using the disk version of the sims 1 on a Windows 11 computer and whenever I try to use your Widescreen Patcher, the "Patch" button is grayed out and won't let me continue. What should I do?

**Comment by FaithBeam** [comment]
@thatcoolmonkey You need to be using a nocd crack for this patch to work.
