### ISSUE TITLE
DDrawCompat 0.3.1 last fully-stable version for The Sims 1

### ISSUE THREAD

**Issue by mrpenguinb** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#64]
With version 0.4.0 a new overlay was added, and the game doesn't run properly on my end. Would appreciate it if other people tested it out and see the performance/smoothness compared to 0.3.1. It's night and day for me.

~**As mentioned in issue 63 on this repo, seems like version 0.3.1 should be the default for the widescreen patcher.**~

**Comment by FaithBeam** [comment]
This is a predicament because ddrawcompat 0.3.1 and 0.3.2 no longer work on my computer for The Sims. [0.3.2](https://github.com/narzoul/DDrawCompat/releases/tag/v0.3.2) was supposed to fix an issue with Windows 11 22H2 but that doesn't seem to be the case for me. Can you tell me your computers specs and Windows version? 

Mine are:
Windows 11, 22H2
CPU: Intel i9-10850k
GPU: RTX 3080
Memory: 32GB

**Comment by mrpenguinb** [comment]
Windows 10 22H2
CPU: Intel i5-10600K
GPU: RTX 3060 8GB
Memory: 32GB

**Comment by FaithBeam** [comment]
Can you try [0.3.2](https://github.com/narzoul/DDrawCompat/releases/tag/v0.3.2) and see if that works for you? I can get that version running on Windows 11.

**Comment by mrpenguinb** [comment]
0.3.2 works fine for me, it has only one change compared to the previous version.

**Comment by mrpenguinb** [comment]
I resolved my lag/stutter issue with 0.4.0 with TS1!
Setting ```DisplayResolution = app``` makes the game perform like it usually does, and is filtered like usual.

Here's my entire config file, **the user in issue 61 should try this config:**
```
# AlternatePixelCenter = off
# BltFilter = point
# Antialiasing = off
# DisplayFilter = bilinear(0)
# FontAntialiasing = app
# FpsLimiter = off
# RenderColorDepth = app
# ResolutionScale = app(1)
# ResolutionScaleFilter = point
# SpriteDetection = off
# SpriteFilter = app
# SpriteTexCoord = app
# TextureFilter = app
# VSync = app
AltTabFix = keepvidmem
DisplayResolution = app
DisplayRefreshRate = desktop
DpiAwareness = app
FpsLimiter = msgloop(60)
FullscreenMode = exclusive
```

**Comment by mrpenguinb** [comment]
@FaithBeam How well goes the game perform for you with 0.4.0 with and without the ```DisplayResolution = app``` config? Interested to know if you've noticed anything.

**Comment by mrpenguinb** [comment]
**FYI** version 4 of DDrawCompat has the option to run the game in borderless fullscreen, to help mitigate against G-Sync issues, as mentioned [here](https://github.com/narzoul/DDrawCompat/issues/133#issuecomment-1260026535) by narzoul
