### ISSUE TITLE
DirectX7 Missing

### ISSUE THREAD

**Issue by mnasty** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#68]
Hello, encountering an issue when attempting to launch the game using any of the 3 provided options. Have tried versions:
-3.3.0
-3.2.3
-2.3.2

Environment:
- Win 7 SP1 / VMWare Fusion 13.02 on MacOS Big Sur 11.7.7
- DirectX9 via directx_June2010_redist (also tried 7 and 8a that comes in the game installer)

Same errors on all versions. Attempted to use *both* the ddraw.dll fixes listed in #64 

1.) DDrawCompat - Program fails to run silently and outputs the following logs:

[Sims_stkdmp_ddraw.txt](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/11595274/Sims_stkdmp_ddraw.txt)
[DDrawCompat-Sims.log](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/11595277/DDrawCompat-Sims.log)

2.) DgVoodoo2 - Get an error saying DirectX 7 could not be found:

<img width="1038" alt="dgv-screen" src="https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/assets/20830151/119a3e6c-6a9a-4c26-9b30-4666a5bd74f4">

3.) None - Program runs but is unusable and crashes just before loading neighborhood. Clearly an issue with the graphics rendering. Screenshot below. Posted the Sims_stkdump log as well for this scenario.

<img width="1330" alt="none-screen" src="https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/assets/20830151/9dd8cedb-ac67-48c6-810c-bd4d2db2ccb1">

[Sims_stkdmp_none.txt](https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/files/11595275/Sims_stkdmp_none.txt)

The DgVoodo2 option appears to be the most promising and I suspect there is simply an environment variable for directx missing but I don't know where to look for it. I've looked through the clef logs but cannot locate anything that looks right in the files that appear to be modified by the program.

Hoping someone here can advise me on a solution. Amazed at your dedication but totally understand. This game is epic and I'd love to relive it again in widescreen :)

**Comment by FaithBeam** [comment]
Are you able to run the game without the patcher? Uninstall the patch if its been installed first.

**Comment by FaithBeam** [comment]
DDraw: I don't think it's going to work in a VM. At least it doesn't for VMware W7 on Windows 11.
DGVoodoo2: Can't really say why it doesn't work for you. Maybe it's some incompatibility with VMware Fusion because it works on my vm.
None: That specific error occurs when you select a resolution that your monitor doesn't support for fullscreen. Since you're in a VM, that makes things a bit weirder. Try a different resolution in the patcher.

You can install the sims and use the patcher on macOS using Wineskin winery. I have a step by step video here if you'd like to give that a try: https://www.youtube.com/watch?v=hOy1boR1_Go

**Comment by mnasty** [comment]
Good catch on the unsupported resolution! I got it working now and here's what I learned:

-Must uncheck 'Use full resolution for retina display' in VMWare settings

-Screen resolution is heavily managed by VMWare tools. Using anything that wasn't the default resolution set by the display driver (1680x1050 in my case) resulted in this unsupported resolution pink screen. The display settings are dynamically managed by a service and it gets very upset even when a lower resolution set in the patcher matches a lower system resolution set manually. It just sets it back when the program is launched thinking it's misbehaving software or I minimized the VM window.

VMWare Tools violently abhors any sort of wrapper. Must use 'None' wrapper 

MUST remove any command line options from the launch shortcut in Properties > Target such as -w or -r1024x768 because these will result in failures after the loading screen.

Load times can be somewhat long (~2 minutes) and the words may stop moving multiple times on the loading screen.

------

Would be interested in using a wine wrapper if they were more reliable constructs.. also nervous about their future on apple silicon.. my new mac comes this week and don't wanna repeat myself.. I think someone will always find a way to make windows run on top of macos somewhat reliably but application specific 'hacks' would suck to manage for each os update.. and when rosetta 2 is revoked.. lol only can hope there is a community developed solution by then..

Thanks for the tip!

**Comment by FaithBeam** [comment]
Cool! Thanks for including the extra information to get it working in your VM. You're right about the wine wrappers. Sometimes it seems like their usefulness is affected by the position of the planets :p

**Comment by mrpenguinb** [comment]
> Cool! Thanks for including the extra information to get it working in your VM. You're right about the wine wrappers. Sometimes it seems like their usefulness is affected by the position of the planets :p

You can say that again

**Comment by nickkeane** [comment]
I'm getting the DX7 not installed/not located issue with dgVoodoo2 on my Laptop w/ Windows 11 Pro. The issue only seems to occur when dgVoodoo2 is set to use my main GPU (RTX 4060 Laptop) and not the integrated GPU (Intel UHD). The integrated GPU seems to work fine.
