### ISSUE TITLE
Can't open the 3.4.0 app (macOS)

### ISSUE THREAD

**Issue by xactionx59** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#73]
Hi!

I can't open the latest version of the patch on my macOS... Thanks!

<img width="802" alt="Capture d’écran 2023-07-20 à 18 35 00" src="https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/assets/38098554/8cb724af-08d4-41ba-8ccc-3072bc08813d">

**Comment by FaithBeam** [comment]
Hello! Open Terminal and enter this command:

```sudo xattr -r -d com.apple.quarantine ~/Downloads/artifacts/Sims1WidescreenPatcher.app/```

and enter your password when Terminal asks. It'll look like this:

<img width="1420" alt="Screenshot 2023-07-20 at 4 03 19 PM" src="https://github.com/FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher/assets/32502411/b4f96f69-8720-44f7-b2b8-48764894f682">

**Comment by xactionx59** [comment]
Hello! It works! Thanks a lot! :)
