### ISSUE TITLE
The app does not open

### ISSUE THREAD

**Issue by Gumballhero123** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#77]
Well yeah when i tried to open the software\app, it is not running. already also running into administrator and yep still not working.. My computer were 64 bit and yes all compability i has reach but it come out none..

Somebody need to help me

**Comment by BlakeGameYT** [comment]
I too have been having this issue with both 3.7.0 and 3.7.1 and i'm running Windows 10 with no anti virus. I does create a .clef which is linked below. 

Link: https://drive.google.com/file/d/1ZrFDcHuf90JuiY_Epq15o1rSzSH6LE5B/view?usp=sharing

**Comment by FaithBeam** [comment]
@BlakeGameYT It says I have to request access to view that link so I did. In the meantime, here is the patcher at 3.6.0 which was unreleased because I didn't think it was worth releasing it at the time. Google drive link because there's a 25mb file size limit on comments.

https://drive.google.com/file/d/1ALv12SWDoQSWLADCGqn6jVxz3RQMd3dS/view?usp=share_link

**Comment by BlakeGameYT** [comment]
@FaithBeam Granted. That's really odd how it needs access i've never encountered that issue before.

The 3.6.0 version also has the same issue with 3.7.x. Only one that still works is 3.4.0 and below. 

https://drive.google.com/file/d/1lc67sK3zf5FJjnBZY-w2uXsFJ9g8k4cv/view?usp=sharing

**Comment by FaithBeam** [comment]
@BlakeGameYT Thank you for the log file. Looks like the feature to detect the Sims install path that was added in 3.6.0 exposed a bad state that wouldn't have happened prior. This does raise a question, is the path to your Sims exe F:\The Sims 1 Starter Pack\Sims.exe? That's the value stored in registry key Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Maxis\The Sims\InstallPath.

In any case, try this updated version: https://drive.google.com/file/d/1O6mNWzYSeP5RL4SwjId0GLDQmusQG6tv/view?usp=sharing

**Comment by BlakeGameYT** [comment]
@FaithBeam My game is installed to my D: drive idk why my F: is involved in anyway shape or form since its my external backup. The 3.7.2 version you sent works perfect and there's no issues anymore.

**Comment by FaithBeam** [comment]
Excellent, thank you for the help! I've released 3.7.2.
