### ISSUE TITLE
StudioTown and MagicTown View Artifacts with 1.2.1

### ISSUE THREAD

**Issue by FaithBeam** [FaithBeam/Sims-1-Complete-Collection-Widescreen-Patcher#8]
Tooltip windows stay over the blue background even though you move your mouse cursor away

![StudioTown](https://i.imgur.com/mv26wiD.png)
![MagicTown](https://i.imgur.com/8CY4BIn.png)

**Comment by NER0888** [comment]
After running this patch as administrator i have this. any idea why?

![Annotation 2020-04-03 143308](https://user-images.githubusercontent.com/62935373/78356530-66f53680-75b8-11ea-86a3-58188608d194.png)
